name: dab
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - python<3.10
  - pip
  - tqdm
  - psycopg2
  - SQLAlchemy
  - pandas
  - Pillow
  - fastapi
  - uvicorn
  - pip:
    - nbdev
    - plotly
    - ftfy
    - schedule
    - psutil
    - nbdev