# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dtd": "boxes.ipynb",
         "vslzr": "boxes.ipynb",
         "model_config_path": "boxes.ipynb",
         "model_checkpoint_path": "boxes.ipynb",
         "device": "boxes.ipynb",
         "args": "boxes.ipynb",
         "checkpoint": "boxes.ipynb",
         "model": "boxes.ipynb",
         "get_boxes": "boxes.ipynb"}

modules = ["boxes.py"]

doc_url = "https://{user}.github.io/dab/"

git_url = "https://github.com/{user}/dab/tree/{branch}/"

def custom_doc_links(name): return None
