# AUTOGENERATED! DO NOT EDIT! File to edit: box_segment.ipynb (unless otherwise specified).

__all__ = ['save_segmented_boxes']

# Cell
import requests
from PIL import Image
from io import BytesIO

from .boxes import *
from .segment import *
from .paths import *

# Cell
def save_segmented_boxes(url,thershold=0.35):
    response = requests.get(url)
    img = Image.open(BytesIO(response.content))
    img,mask = get_food_segment(img)
    boxes = get_boxes(img,thershold=thershold)
    photo_id = url.split('/')[-1]
    for id, box in enumerate(boxes): img.crop(box).save(fragment_reference_images_path/f'{photo_id}_{id}.jpg')
    return boxes,mask.tolist()