name: dab
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - python<3.10
  - pip
  - tqdm
  - psycopg2
  - SQLAlchemy
  - pandas
  - Pillow
  - voila
  - fastapi
  - uvicorn
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.11.0+cu115
    - torchvision==0.12.0+cu115
    - transformers
    - tendo
    - dateparser
    - transformers
    - matplotlib
    - plotly
    - ftfy
    - schedule
    - psutil
    - docker
    - pymilvus
    - wrapt
    - nbdev

    - cython
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI&egg=pycocotools
    - submitit
    - git+https://github.com/cocodataset/panopticapi.git#egg=panopticapi
    - scipy
    - termcolor
    - addict
    - yapf
    - timm